# Load necessary libraries
library(tidyverse)
library(lubridate)

# ---- Step 1: Load AQI Data ----
# This file should be generated by the aqi_data_acquisition.R script
# Source: EPA AQS data queried via RAQSAPI and processed to daily AQI using Ellen Considine's function

aqi_data <- read_csv("data/missoula_pm25_aqi_daily.csv") %>%
  mutate(date = as_date(datetime)) %>%
  select(date, aqi)

# ---- Step 2: Define Home Game Event Dates (2022–2024) ----
# Source: Official UM Grizzlies Football schedules

event_dates <- tibble(
  event_date = as_date(c(
    # 2022 Home Games
    "2022-09-03", "2022-09-10", "2022-09-24", "2022-10-15", "2022-11-05", "2022-11-12", "2022-11-26",
    # 2023 Home Games
    "2023-09-02", "2023-09-16", "2023-09-30", "2023-10-28", "2023-11-04", "2023-11-18", "2023-12-02", "2023-12-08", "2023-12-16",
    # 2024 Home Games
    "2024-08-31", "2024-09-14", "2024-09-21", "2024-10-05", "2024-10-12", "2024-11-09", "2024-11-16", "2024-11-30"
  )),
  event_name = c(
    "Northwestern State", "South Dakota", "Portland State", "Idaho", "Cal Poly", "Eastern Washington", "Southeast Missouri State",
    "Butler", "Ferris State", "Idaho State", "Northern Colorado", "Sacramento State", "Montana State", "Delaware", "Furman", "North Dakota State",
    "Missouri State", "Morehead State", "Western Carolina", "Weber State", "Northern Arizona", "UC Davis", "Portland State", "Tennessee State"
  )
)

# ---- Step 3: Assign Base Attendance ----
set.seed(42)  # for reproducibility

event_dates <- event_dates %>%
  mutate(
    base_attendance = case_when(
      str_detect(event_name, "Montana State|Playoffs|North Dakota State|Furman|Delaware") ~ sample(26500:27000, n(), replace = TRUE),
      str_detect(event_name, "(State|Eastern|Northern|Southern|Weber|UC|Idaho)") ~ sample(25400:26200, n(), replace = TRUE),
      TRUE ~ sample(24500:25500, n(), replace = TRUE)
    )
  )

# ---- Step 4: Join with AQI and Simulate Realized Attendance ----
impact_factor <- 0.12  # 12% reduction per 100 AQI points

synthetic_attendance <- event_dates %>%
  left_join(aqi_data, by = c("event_date" = "date")) %>%
  mutate(
    aqi = if_else(is.na(aqi), 30, aqi),  # fill in low AQI for missing days
    realized_attendance = round(
      base_attendance * (1 - impact_factor * (aqi / 100)) + rnorm(n(), mean = 0, sd = 750)
    ),
    realized_attendance = pmax(realized_attendance, 0)  # ensure no negatives
  )

# ---- Step 5: Save Synthetic Dataset ----
write_csv(synthetic_attendance, "data/synthetic_event_attendance.csv")

# Preview
print(synthetic_attendance)
